# Generated by Django 5.2.8 on 2025-11-17 01:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_doctor_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'ordering': ['examination_date', 'examination_time']},
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='examination_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('confirmed', 'Terkonfirmasi'), ('completed', 'Selesai'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedule',
            name='status',
            field=models.CharField(choices=[('available', 'Tersedia'), ('booked', 'Terbooking'), ('unavailable', 'Tidak Tersedia')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.doctor'),
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('doctor', 'examination_date', 'examination_time')},
        ),
    ]
