# Generated by Django 5.2.8 on 2025-11-17 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_payment_options_remove_payment_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hours_end',
            field=models.TimeField(default='17:00'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hours_start',
            field=models.TimeField(default='08:00'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='confirmation_status',
            field=models.CharField(choices=[('pending', 'Menunggu Konfirmasi'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DoctorLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='core.doctor')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='DoctorAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.doctor')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
                'unique_together': {('doctor', 'day_of_week')},
            },
        ),
    ]
